# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61udio_service.proto\x12\x07wazobia\"D\n\x0c\x41udioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\"m\n\rAudioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x15\n\rerror_message\x18\x05 \x01(\t\" \n\rHealthRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"B\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t2\x91\x01\n\x0c\x41udioService\x12?\n\x0cProcessAudio\x12\x15.wazobia.AudioRequest\x1a\x16.wazobia.AudioResponse\"\x00\x12@\n\x0bHealthCheck\x12\x16.wazobia.HealthRequest\x1a\x17.wazobia.HealthResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=32
  _globals['_AUDIOREQUEST']._serialized_end=100
  _globals['_AUDIORESPONSE']._serialized_start=102
  _globals['_AUDIORESPONSE']._serialized_end=211
  _globals['_HEALTHREQUEST']._serialized_start=213
  _globals['_HEALTHREQUEST']._serialized_end=245
  _globals['_HEALTHRESPONSE']._serialized_start=247
  _globals['_HEALTHRESPONSE']._serialized_end=313
  _globals['_AUDIOSERVICE']._serialized_start=316
  _globals['_AUDIOSERVICE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
